

name: CI


on:

  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]


  workflow_dispatch:


jobs:

  build:

    runs-on: macos-11


    steps:

      - uses: actions/checkout@v2


      - name: 安装md5校验工具
        run: brew install md5sha1sum


      - name: 运转构建脚本
        run: |
          mkdir -p build
          ./build.sh
          
      - name: 打包上传工作件
        uses: actions/upload-artifact@v2
        with:
          name: mac_bios_build
          path: build/*.bin
          
      - name: 上传发布版本
        if: github.event_name == 'release'
        uses: svenstaro/upload-release-action@483c1e56f95e88835747b1c7c60581215016cbf2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: build/*.bin
          tag: ${{ github.ref }}
          file_glob: true
      - name: 上传发布版本
        if: github.event_name == 'release'
        uses: svenstaro/upload-release-action@483c1e56f95e88835747b1c7c60581215016cbf2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: build/*.txt
          tag: ${{ github.ref }}
          file_glob: true
