

name: CI


on:

  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]


  workflow_dispatch:


jobs:

  build:

    runs-on: macos-11


    steps:

      - uses: actions/checkout@v2


      - name: 安装md5校验工具
        run: brew install md5sha1sum


      - name: Run a multi-line script
        run: |
          mkdir -p build
          ./build.sh
